runs:
  - name: "2024_1Y_W_SP500"
    universe: "0#.SPX"
    start: "2024-01-01"
    end: "2024-12-31"
    freq: "W"
    output: "Output/"
  - name: "2023_1Y_W_SP500"
    universe: "0#.SPX"
    start: "2023-01-01"
    end: "2023-12-31"
    freq: "W"
    output: "Output/"
  - name: "2022_1Y_W_SP500"
    universe: "0#.SPX"
    start: "2022-01-01"
    end: "2022-12-31"
    freq: "W"
    output: "Output/"
  - name: "2024_2Y_W_SP500"
    universe: "0#.SPX"
    start: "2023-01-01"
    end: "2024-12-31"
    freq: "W"
    output: "Output/"
  - name: "2023_2Y_W_SP500"
    universe: "0#.SPX"
    start: "2022-01-01"
    end: "2023-12-31"
    freq: "W"
    output: "Output/"